// Package identity's wordlist. adjectives and nouns are curated together,
// not independently: the hazard is a combination nobody reviewed, so every
// entry was chosen picturing it next to every entry in the other slice,
// favoring plain, concrete, neutral vocabulary.
//
// Every entry is lowercase a-z only and at most 8 characters. Canonical
// enforces the same cap on identities this package did not mint.
package identity

var adjectives = []string{
	"airy", "alert", "amber", "ample", "ancient", "arid", "baggy", "balmy",
	"beige", "big", "black", "bland", "blue", "blunt", "bold", "brave",
	"breezy", "bright", "brisk", "broad", "bronze", "brown", "bumpy", "burly",
	"calm", "cheeky", "cheery", "chewy", "chilly", "chipper", "chirpy", "chunky",
	"clear", "clever", "cloudy", "cool", "copper", "coral", "coy", "cozy",
	"cramped", "crimson", "crisp", "crude", "crunchy", "cunning", "cyan", "dapper",
	"daring", "dark", "dashing", "dense", "dim", "docile", "downy", "drowsy",
	"dull", "dusty", "eager", "earnest", "emerald", "faded", "fancy", "fast",
	"feisty", "feral", "fierce", "firm", "flat", "fluffy", "foggy", "fresh",
	"frosty", "frugal", "fuzzy", "gallant", "gaunt", "genial", "gentle", "giant",
	"glossy", "gold", "grainy", "gray", "green", "gruff", "grumpy", "happy",
	"hardy", "harsh", "hasty", "hazy", "hefty", "honest", "huge", "humble",
	"humid", "husky", "icy", "indigo", "ivory", "jade", "jaunty", "jolly",
	"jovial", "jumpy", "keen", "kind", "kindly", "lanky", "lax", "lazy",
	"leathery", "lively", "loose", "loyal", "maroon", "matte", "meek", "mellow",
	"merry", "messy", "mild", "mini", "mint", "misty", "modern", "muted",
	"naive", "narrow", "navy", "neat", "nimble", "noble", "nosy", "odd",
	"olive", "oval", "pale", "pastel", "peppy", "petite", "pink", "placid",
	"plain", "plucky", "plump", "polished", "portly", "posh", "prim", "proud",
	"punctual", "quaint", "quick", "quiet", "rainy", "rare", "red", "restless",
	"retro", "rich", "roomy", "rose", "rough", "round", "ruby", "rugged",
	"rust", "rustic", "salty", "sand", "sandy", "sassy", "satiny", "scant",
	"scarlet", "sepia", "shabby", "sharp", "shiny", "short", "shy", "silken",
	"silky", "silver", "sleek", "slim", "slow", "sluggish", "sly", "small",
	"smooth", "smug", "snappy", "snowy", "snug", "soft", "solemn", "sour",
	"spare", "sparse", "speedy", "spicy", "spongy", "spry", "spunky", "square",
	"stale", "stern", "stocky", "stoic", "stormy", "stout", "stray", "strict",
	"stuffy", "sturdy", "subtle", "sunny", "svelte", "sweet", "tall", "tame",
	"tan", "tangy", "tardy", "taut", "teal", "thick", "thin", "tidy",
	"tight", "timid", "tiny", "trim", "vain", "vast", "velvet", "violet",
	"vivid", "warm", "waxy", "white", "wide", "wild", "windy", "wiry",
	"wise", "witty", "woolly", "worn", "young", "zesty", "zippy",
}

var nouns = []string{
	"abacus", "alder", "amulet", "anchor", "anemone", "antelope", "anvil", "apple",
	"apron", "archer", "aspen", "asteroid", "atoll", "aurora", "badger", "balloon",
	"bamboo", "banjo", "banner", "barrel", "basalt", "basket", "bayou", "beaver",
	"bell", "beret", "berry", "birch", "bison", "blanket", "bobbin", "bobcat",
	"bonnet", "boot", "boulder", "breeze", "brooch", "broom", "bucket", "buckle",
	"button", "buzzard", "cabin", "cabinet", "caboose", "camera", "candle", "canoe",
	"canteen", "canvas", "canyon", "cape", "cardinal", "carriage", "cave", "cavern",
	"cedar", "chest", "chime", "chipmunk", "chisel", "clam", "clarinet", "cliff",
	"cloak", "clock", "cloud", "clover", "comet", "compass", "condor", "cottage",
	"cougar", "crab", "crane", "crate", "cricket", "crow", "crystal", "curtain",
	"cushion", "cymbal", "daisy", "date", "daybreak", "delta", "dew", "dice",
	"dolphin", "domino", "drawer", "drum", "dune", "easel", "eclipse", "egret",
	"elk", "elm", "falcon", "fawn", "fern", "ferret", "fiddle", "fig",
	"finch", "firefly", "fjord", "flag", "flute", "fresco", "frost", "galaxy",
	"garnet", "gazebo", "gazelle", "geyser", "glacier", "goblet", "gong", "gopher",
	"granite", "grape", "grotto", "guava", "hammer", "hamper", "harbor", "harp",
	"haze", "heather", "hedgehog", "heron", "horizon", "hornet", "iceberg", "inkwell",
	"ivy", "jaguar", "jasmine", "jay", "jetty", "jug", "kayak", "kestrel",
	"kettle", "kite", "kiwi", "knapsack", "ladle", "lagoon", "lantern", "lattice",
	"ledger", "lemon", "lilac", "lime", "lobster", "locket", "loom", "lotus",
	"lynx", "magpie", "manatee", "mango", "maple", "marble", "marmot", "marsh",
	"mast", "meadow", "medal", "melon", "mesa", "meteor", "minnow", "mirror",
	"mist", "mitten", "moon", "moonbeam", "moose", "mortar", "mosaic", "moss",
	"mural", "mussel", "narwhal", "nebula", "needle", "oak", "oar", "oasis",
	"obsidian", "octopus", "onyx", "opal", "orchid", "oriole", "osprey", "otter",
	"oyster", "paddle", "palette", "panther", "papaya", "parakeet", "parrot", "peach",
	"pear", "pebble", "pelican", "pennant", "pestle", "pier", "pillow", "pine",
	"planet", "plateau", "plover", "plum", "poplar", "possum", "pouch", "prairie",
	"puffin", "puzzle", "quarry", "quartz", "quasar", "quill", "quilt", "rabbit",
	"raccoon", "raft", "rainbow", "raindrop", "raven", "reef", "ribbon", "ridge",
	"robin", "rudder", "sailboat", "salmon", "sandal", "sash", "satchel", "scarf",
	"schooner", "scroll", "seahorse", "seal", "seashell", "sequoia", "shelf", "shrimp",
	"skunk", "slate", "sled", "sleigh", "slipper", "sparrow", "spatula", "spindle",
	"spruce", "squid", "squirrel", "stag", "starfish", "stork", "summit", "sunrise",
	"sunset", "swallow", "swamp", "swift", "tanager", "tapestry", "teapot", "thermos",
	"thimble", "thistle", "thread", "topaz", "toucan", "trellis", "trophy", "trowel",
	"trumpet", "trunk", "tulip", "tundra", "turtle", "twilight", "urchin", "urn",
	"valley", "vase", "vulture", "wagon", "wallet", "walrus", "warbler", "weasel",
	"wharf", "whisk", "whistle", "willow", "windmill", "wren", "wrench", "zenith",
}
