#!/usr/bin/env bash
# Regenerates THIRD-PARTY-NOTICES from the modules ACTUALLY LINKED into a
# built binary, read back out of it with `go version -m`.
#
# Reading the binary rather than go.mod is the whole point. go.mod lists what
# the module requires; the binary lists what shipped. Those differ -- go.mod
# names 9 direct requirements while 27 modules are linked -- and the notice
# obligation attaches to what is distributed.
#
# It FAILS rather than skipping when a license cannot be found for a module.
# A notices file that silently omits a dependency is worse than none: it
# looks complete.
set -euo pipefail

BIN=${1:-}
OUT=${OUT:-THIRD-PARTY-NOTICES}
[ -n "$BIN" ] || { echo "usage: $0 <path-to-built-binary>" >&2; exit 2; }
[ -f "$BIN" ] || { echo "no such binary: $BIN" >&2; exit 2; }

MODCACHE=$(go env GOMODCACHE)

# Go escapes uppercase letters in module cache paths as !lowercase.
escape() { printf '%s' "$1" | awk '{n=split($0,a,"");s="";for(i=1;i<=n;i++){c=a[i];if(c~/[A-Z]/)s=s"!"tolower(c);else s=s c}print s}'; }

mods=$(go version -m "$BIN" | awk '$1=="dep"{print $2"@"$3}' | sort -u)
[ -n "$mods" ] || { echo "no dependencies found in $BIN -- is it a Go binary?" >&2; exit 1; }

tmp=$(mktemp); missing=0; count=0
{
  echo "THIRD-PARTY NOTICES"
  echo
  echo "Draftplane incorporates the following third-party open source"
  echo "components. Each is licensed under its own terms, reproduced in full below."
  echo "Those terms govern those components and are not limited by the Software's"
  echo "own MIT licence (LICENSE)."
  echo
  echo "This file is generated by scripts/gen-third-party-notices.sh from the"
  echo "modules linked into the built binary. Do not edit it by hand."
  echo
  echo "Components:"
  while read -r m; do echo "  - ${m}"; done <<< "$mods"
  echo
} >> "$tmp"

while read -r m; do
  path="${m%@*}"; ver="${m##*@}"
  dir="$MODCACHE/$(escape "$path")@${ver}"
  lic=$(find "$dir" -maxdepth 2 \( -iname 'LICENSE' -o -iname 'LICENSE.*' \
                                  -o -iname 'LICENCE' -o -iname 'LICENCE.*' \
                                  -o -iname 'COPYING' -o -iname 'COPYING.*' \) \
        2>/dev/null | sort | head -1 || true)
  if [ -z "$lic" ]; then
    echo "MISSING LICENSE: $m (looked in $dir)" >&2; missing=$((missing+1)); continue
  fi
  {
    printf '%s\n' "================================================================================"
    printf '%s\n' "$m"
    printf '%s\n' "================================================================================"
    echo
    cat "$lic"
    echo
    # Apache-2.0 requires any NOTICE file to travel with redistributions.
    notice=$(find "$dir" -maxdepth 2 -iname 'NOTICE*' 2>/dev/null | sort | head -1 || true)
    if [ -n "$notice" ]; then echo "--- NOTICE ---"; echo; cat "$notice"; echo; fi
  } >> "$tmp"
  count=$((count+1))
done <<< "$mods"

if [ "$missing" -gt 0 ]; then
  echo "refusing to write $OUT: $missing module(s) have no license file" >&2
  rm -f "$tmp"; exit 1
fi

mv "$tmp" "$OUT"
echo "wrote $OUT: $count components"
